import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Footer from "@/components/layout/Footer";
import NavBar from "@/components/layout/NavBar";

const satoshi = localFont({
  src: [
    {
      path: "./fonts/satoshi/Satoshi-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/satoshi/Satoshi-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/satoshi/Satoshi-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/satoshi/Satoshi-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/satoshi/Satoshi-Black.woff2",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-satoshi",
  display: "swap",
});
const helvetica_compressed = localFont({
  src: [
    {
      path: "./fonts/helveticacompressed/Helvetica-Compressed.otf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-helvetica-compressed",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full w-full">
      <body
        className={`${satoshi.variable} ${helvetica_compressed.variable} antialiased h-full w-full`}
      >
        <div className="h-full w-full relative">
          <NavBar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
